This is makeindex, version 2.15 [MiKTeX 2.9.6630 64-bit] (kpathsea + Thai support).
Scanning style file ./Bachelorarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Bachelorarbeit.acn....done (277 entries accepted, 0 rejected).
Sorting entries.....done (2552 comparisons).
Generating output file Bachelorarbeit.acr....done (151 lines written, 0 warnings).
Output written in Bachelorarbeit.acr.
Transcript written in Bachelorarbeit.alg.
